spring:
    datasource:
        url: jdbc:mysql://localhost:3306/software_design?serverTimeZone=UTC
        username: root
        password: Zxt6830i###
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.proxy.DruidDriver

server:
    port: 8080
mybatis:
    mapper-locations: "classpath:mapper/*.xml"

